spring.application.name=RecipeBuilder
spring.ai.google.genai.api-key=${API_KEY}
spring.ai.google.genai.embedding.api-key=${API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.project-id=${PROJECT_ID}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
server.port=8081




# ==========================================
# MySQL Database Configuration
# ==========================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/recipe_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ==========================================
# JPA / Hibernate Configuration
# ==========================================
# Updates the schema automatically (good for dev, use Flyway/Liquibase for prod)
spring.jpa.hibernate.ddl-auto=update
# Shows the SQL queries in the console
spring.jpa.show-sql=true
# Formats the SQL queries in the console to be readable
spring.jpa.properties.hibernate.format_sql=true

